// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoMZnhZVGIBmWyp80g3_JcUYDEZg5waQo',
    appId: '1:902426529724:web:11193edecb79ce6be8a5b9',
    messagingSenderId: '902426529724',
    projectId: 'gcechs-org',
    authDomain: 'gcechs-org.firebaseapp.com',
    databaseURL: 'https://gcechs-org-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gcechs-org.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVzbEUebV1Wrahkmw0VjE_dMGlinOjZZU',
    appId: '1:902426529724:android:cb3026c7cda8efdee8a5b9',
    messagingSenderId: '902426529724',
    projectId: 'gcechs-org',
    databaseURL: 'https://gcechs-org-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gcechs-org.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8rB_FVnrsVBN9sHqCjAzgmEitn0Hq4jo',
    appId: '1:902426529724:ios:997dffcc2bbe175ce8a5b9',
    messagingSenderId: '902426529724',
    projectId: 'gcechs-org',
    databaseURL: 'https://gcechs-org-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gcechs-org.appspot.com',
    androidClientId: '902426529724-8v9528b1k8r9pukp845j9st5c0osde93.apps.googleusercontent.com',
    iosClientId: '902426529724-oluoaqbfbg4qafeqqutob113mqvkt0ma.apps.googleusercontent.com',
    iosBundleId: 'com.example.housingsociety',
  );
}
