// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVzbEUebV1Wrahkmw0VjE_dMGlinOjZZU',
    appId: '1:902426529724:android:394feac783f3fe47e8a5b9',
    messagingSenderId: '902426529724',
    projectId: 'gcechs-org',
    databaseURL: 'https://gcechs-org-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gcechs-org.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8rB_FVnrsVBN9sHqCjAzgmEitn0Hq4jo',
    appId: '1:902426529724:ios:7a2c0515ebafd5aee8a5b9',
    messagingSenderId: '902426529724',
    projectId: 'gcechs-org',
    databaseURL: 'https://gcechs-org-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gcechs-org.appspot.com',
    androidClientId: '902426529724-mgshm74v2n7bdomlmd14db3a0e11him9.apps.googleusercontent.com',
    iosClientId: '902426529724-3cf230gkokqtdps4p177jr0du7fjbsas.apps.googleusercontent.com',
    iosBundleId: 'com.gcechs.app',
  );
}
